### ISSUE TITLE
Results from previously run search do not appear on screen

### ISSUE THREAD

**Issue by nOkuda** [jeffkinnison/tesserae-frontend#10]
When re-running a search that has already been performed, the user interface does not display the results. It does not seem to be an issue with the database, since the Network information in the Developer Tools shows that the results are coming back. In fact, I can see the response object with the Developer Tools. It's somehow not getting put into the interface.

**Comment by jeffkinnison** [comment]
Re-running in what way? Clicking a second time while the results are still there? Or running a new search?

**Comment by nOkuda** [comment]
Both.

**Comment by jeffkinnison** [comment]
This should be fixed in the most recent push.

**Comment by nOkuda** [comment]
Confirmed: recent push seems to have fixed this problem.
