### ISSUE TITLE
Latin and Greek searches not returning parallels

### ISSUE THREAD

**Issue by nacoffee** [jeffkinnison/tesserae-frontend#3]
Basic test of the Latin search returned no parallels, only a "Finding parallels." messaage and spinning symbol.

Search/Latin.
Source text selections: Vergil, Aeneid
Target text selections: Vergil, Georgics
Search with default options.
After two minutes of just "Finding Parallels" and the spinning circle, search failed and no results were returned.

Same issue for Greek.

Search/Greek
Source text: Homer, Iliad
Target text: Apollonius, Argonautica
Search with default options.
Same result as above.

**Comment by jeffkinnison** [comment]
Needs more testing on Olivia before I'm satisfied this is fixed.

**Comment by jeffkinnison** [comment]
This should be fully fixed.
